# Gol 1 - con jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 12,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 1, asistencia Jugador 2",
  "partido_id": 1,
  "equipo_id": 1,
  "jugador_id": 1,
  "jugador_asociado_id": 2
}

###

# Gol 2 - con jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 28,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 6, asistencia Jugador 9",
  "partido_id": 1,
  "equipo_id": 2,
  "jugador_id": 6,
  "jugador_asociado_id": 9
}

###

# Gol 3 - con jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 33,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 11, asistencia Jugador 14",
  "partido_id": 2,
  "equipo_id": 3,
  "jugador_id": 11,
  "jugador_asociado_id": 14
}

###

# Gol 4 - con jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 47,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 7, asistencia Jugador 10",
  "partido_id": 3,
  "equipo_id": 2,
  "jugador_id": 7,
  "jugador_asociado_id": 10
}

###

# Gol 5 - con jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 55,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 19, asistencia Jugador 16",
  "partido_id": 4,
  "equipo_id": 4,
  "jugador_id": 19,
  "jugador_asociado_id": 16
}

###

# Gol 6 - sin jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 9,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 16",
  "partido_id": 2,
  "equipo_id": 4,
  "jugador_id": 16
}

###

# Gol 7 - sin jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 61,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 3",
  "partido_id": 4,
  "equipo_id": 1,
  "jugador_id": 3
}

###

# Gol 8 - sin jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 72,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 21",
  "partido_id": 5,
  "equipo_id": 5,
  "jugador_id": 21
}

###

# Gol 9 - sin jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 38,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 25",
  "partido_id": 3,
  "equipo_id": 5,
  "jugador_id": 25
}

###

# Gol 10 - sin jugador asociado
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 85,
  "tipo": "gol",
  "descripcion": "Gol de Jugador 13",
  "partido_id": 5,
  "equipo_id": 3,
  "jugador_id": 13
}