# Tarjeta amarilla - Jugador 3 en Partido 1
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 15,
  "tipo": "tarjeta_amarilla",
  "descripcion": "Tarjeta por entrada a Jugador 3",
  "partido_id": 1,
  "equipo_id": 1,
  "jugador_id": 3
}

###

# Tarjeta amarilla - Jugador 9 en Partido 3
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 33,
  "tipo": "tarjeta_amarilla",
  "descripcion": "Falta táctica a Jugador 9",
  "partido_id": 3,
  "equipo_id": 2,
  "jugador_id": 9
}

###

# Tarjeta roja - Jugador 16 en Partido 4
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 78,
  "tipo": "tarjeta_roja",
  "descripcion": "Conducta violenta de Jugador 16",
  "partido_id": 4,
  "equipo_id": 4,
  "jugador_id": 16
}

###

# Tarjeta roja - Jugador 22 en Partido 5
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 44,
  "tipo": "tarjeta_roja",
  "descripcion": "Entrada peligrosa de Jugador 22",
  "partido_id": 5,
  "equipo_id": 5,
  "jugador_id": 22
}

###

# Tarjeta amarilla - Jugador 13 en Partido 2
POST http://127.0.0.1:8000/eventos/
Content-Type: application/json

{
  "minuto": 60,
  "tipo": "tarjeta_amarilla",
  "descripcion": "Simulación de Jugador 13",
  "partido_id": 2,
  "equipo_id": 3,
  "jugador_id": 13
}